apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess
spec:
  replicas: 2  # Specify the number of replicas
  selector:
    matchLabels:
      app: chess
  template:
    metadata:
      labels:
        app: chess
    spec:
      containers:
      - name: chess
        image: pramodm93/chess:latest
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: chess-svc
spec:
  type: LoadBalancer
  selector:
    app: chess
  ports:
  - port: 80
    targetPort: 80
